name: Run on merged & approved PR

on:
  pull_request:
    types: [closed]

jobs:
  detect:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    outputs:
      deploy:     ${{ steps.detect.outputs.deploy }}
      has_errors: ${{ steps.detect.outputs.has_errors }}
      matrix:     ${{ steps.detect.outputs.matrix }}
      all_changed: ${{ steps.detect.outputs.all_changed }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get matrix and deploy flag
        id: detect
        uses: ./.github/actions/get-matrix-and-deploy-flag
        with:
          base_sha: ${{ github.event.pull_request.base.sha }}
          head_sha: ${{ github.event.pull_request.head.sha }}
          validate: "true"

      - name: Show outputs (optional)
        run: |
          echo "deploy=${{ steps.detect.outputs.deploy }}"
          echo "has_errors=${{ steps.detect.outputs.has_errors }}"
          echo "matrix=${{ steps.detect.outputs.matrix }}"
          echo -e "all_changed:\n${{ steps.detect.outputs.all_changed }}"

  build:
    needs: detect
    if: ${{ needs.detect.outputs.deploy == 'true' && needs.detect.outputs.has_errors == 'false' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        usecase: ${{ fromJson(needs.detect.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "Building for ${{ matrix.usecase }}"
